# Example Spring Boot YAML configuration
server:
  port: 8075

git:
  local: /tmp/git
  remote-branch: main

app:
  basic-auth-username: user
  basic-auth-password: random-secret

scheduling:
  push:
    initial-delay: 10000
    pause-delay: 5000
