name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  build-service-broker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  build-cli:
    timeout-minutes: 3 # Generally our pipeline takes 1 minute to build everything.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.21"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno # see https://deno.land/manual/linking_to_external_code
          key: ${{ runner.os }}-deno # it seems there's no particular cache keying required
          restore-keys: |
            ${{ runner.os }}-deno
      - run: |
          deno --version
          deno info

          cd cli
          ./build.sh

          cd test
          ./all.sh ../bin/unipipe
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: unipipe-cli
          path: |
            cli/bin/unipipe-cli-*
